# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Teni Music Studio"
description: "Welcome to Teni's Music Studio, your source for fresh beats and musical inspiration."
email: tenixxxv@gmail.com

# Blog logo and cover
logo: "assets/images/IMG_1865.jpeg"
float_logo: false
cover: "assets/images/wes-hicks-MEL-jJnm7RQ-unsplash.jpg"

# Author info
name: "Teni"
author: "Teni"
author_image: "assets/images/IMG_1865.jpeg"

# Pagination
paginate: 5
paginate_path: "/page:num"

# Site URL
url: "https://tmanome.github.io"
baseurl: ""

# Social media and sharing
twitter_handle: "Foxy.beatz"

social:
  - icon: twitter
    url: https://x.com/foxy_beatz_?s=21&t=1rk3H6qlUdyFc_Gs3elv4Q
    desc: Follow me on Twitter
    share_url: https://x.com/foxy_beatz_?s=21&t=1rk3H6qlUdyFc_Gs3elv4Q
    share_title: ?text=
    share_link: "&url="

  - icon: github
    url: https://github.com
    desc: Fork me on GitHub
    share_url: https://github.com
    share_title:
    share_link:

# Uncomment to enable Disqus comments
#disqus: your-disqus-shortname

# Uncomment and replace UA-XXXXX-X to enable Google Analytics
#google_analytics: UA-XXXXX-X
