# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Teni Music Studio"
description: "音樂人雜記與日誌"
email: "tenixxxv@gmail.com"

# Blog logo and cover images
logo: "assets/images/IMG_1865.jpeg"
float_logo: false
cover: "assets/images/wes-hicks-MEL-jJnm7RQ-unsplash.jpg"

# Author information
author: "Teni"
author_image: "assets/images/IMG_1865.jpeg"

# Pagination
paginate: 5
paginate_path: "/page:num"

# Site URL settings (Update with your own site details)
url: "https://tmanome.github.io"
baseurl: "" # 如果你的網站不是在根目錄，這裡要填寫子目錄路徑

# Social media settings
twitter_handle: "Foxy.beatz"

social:
  - icon: twitter
    url: "https://x.com/foxy_beatz_?s=21&t=1rk3H6qlUdyFc_Gs3elv4Q"
    desc: "Follow me on Twitter"

  - icon: github
    url: "https://github.com"
    desc: "Fork me on GitHub"

# Exclude unnecessary files and directories from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md
  - .github

# Include files or folders if needed
include:
  - _pages
  - _posts

# Markdown and encoding settings
markdown: kramdown
highlighter: rouge
encoding: "utf-8"

# Permalinks structure (可根據需求調整)
permalink: /:categories/:year/:month/:day/:title/

# Enable Disqus comments (optional)
# disqus: your-disqus-shortname

# Enable Google Analytics (optional)
# google_analytics: UA-XXXXX-X

# Jemoji configuration (for emojis support)
jemoji:
  emoji_dir: "assets/images/emoji" # 可選的，指定自訂表情符號目錄

# Build configurations
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Teni"
