# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Teni Music Studio"
description: > # this means to ignore newlines until "email:"
   

email: tenixxxv@gmail.mail
#blog logo
logo: "assets/images/IMG_1865.jpeg"
float_logo: false # true, false (default)

# blog cover
cover: "assets/images/wes-hicks-MEL-jJnm7RQ-unsplash.jpg"

name: 'Teni'
author: 'Teni'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://tmanome.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: 'Foxy.beatz'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://x.com/foxy_beatz_?s=21&t=1rk3H6qlUdyFc_Gs3elv4Q
    desc: Follow me on twitter
    share_url: https://x.com/foxy_beatz_?s=21&t=1rk3H6qlUdyFc_Gs3elv4Q
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com
    desc:	Fork me on github
    share_url: https://github.com
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
